version: '2'

services:
  fastapi:
    build:
      context: ./
      dockerfile: ./src/fastapi/Dockerfile
    ports:
      - 80:8000
    volumes:
      - database:/data
    environment:
      - DATABASE_URI

  api_cache:
    build:
      context: ./
      dockerfile: ./src/api_cache/Dockerfile
    volumes:
      - database:/data
    environment:
      - ETH_PROVIDER
      - ETHERSCAN_TOKEN
      - FTM_PROVIDER
      - FTMSCAN_TOKEN
      - DATABASE_URI

volumes:
  database: